### ISSUE TITLE
NBT Stacking Issues

### ISSUE THREAD

**Issue by HJellybean327** [ShadowKing21228/Bauble-Mounts#2]
Causes items to not stack due to NBT data.

https://github.com/user-attachments/assets/8c424c66-35a7-4aa9-af40-f2210944fdde

Edit: Mod version 0.5.1 - Forge Version 47.3.0

**Comment by Not-February** [comment]
I am also experiencing this issue and recently narrowed it down to this mod.

Functionally, it occurs when you have an existing stack of items in your inventory and try to pick up a stack from another source, and is easily reproducible by just placing and breaking torches and examining the NBT tags of the now-separate item stacks.

The torches that were still in your inventory when you pick up the broken ones get an empty `{}` NBT tag attached to them and the ones that you just picked up have no tag at all, so they won't stack with each other. This happens with all such otherwise identical items when obtained from sources like being picked up from the world or found in loot chests/similar. Separated item stacks will merge if dropped on the ground with each other and remove the extra `{}` tag from them.

It's functionally identical what is described [in this Reddit thread](https://www.reddit.com/r/feedthebeast/comments/1g22dy6/comment/lrn4nd9/).

I was able to reproduce this behavior with only the following mods installed(this mod and its dependencies):

MC 1.20.1
Forge 47.3.0
Architectury API 9.2.14
Curios API 5.11.0
SDM UI Lib 1.8.2
Bauble Mounts 0.5.1

**Comment by ShadowKing21228** [comment]
Thanks for finding the bug, it has already been fixed in the new version, you can download it on Curse and Modrinth. It's a pity I didn't notice it earlier.
